# 1. 예외와 예외 클래스

- 예외란 **사용자의 잘못된 조작** 또는 **개발자의 잘못된 코딩**으로 인해 발생하는 프로그램 오류를 말한다.
- 예외가 발생되면 프로그램은 곧바로 종료된다는 점에서는 에러와 동일하다.
- 그러나 예외는 **예외 처리(Exception Handling)** 를 통해 프로그램을 종료하지 않고 **정상 실행 상태가 유지**되도록 할 수 있다.

<br>

- 예외는 **일반 예외(Exception)** 와 **실행 예외(Runtime Exception)** 가 있다.
- 일반 예외는 **컴파일러 체크 예외**라고도 하는데, 자바 소스를 컴파일하는 과정에서 예외 처리 코드가 필요한지 검사하기 때문이다.
- 만약 예외 처리 코드가 없다면 컴파일 오류가 발생한다.
- 실행 예외는 컴파일하는 과정에서 예외 처리 코드를 검사하지 않는 예외를 말한다.
- 컴파일 시 예외 처리를 확인하는 차이일 뿐, 두 가지 예외는 모두 예외 처리가 필요하며, 자바에서는 예외를 **클래스로 관리**한다.
- JVM은 프로그램을 실행하는 도중에 예외가 발생하면 해당 예외 클래스로 객체를 생성하고, 예외 처리 코드에서 예외 객체를 이용할 수 있도록 해준다.
- 모든 예외 클래스들은 다음과 같이 **java.lang.Exception 클래스를 상속**받는다.

![예외 종류](https://user-images.githubusercontent.com/47477359/144597109-d4dbd0fe-528c-4c53-ba6e-5d1bf3db0b3c.png)

- 일반 예외는 **Exception을 상속**받지만 RuntimeException을 상속받지 않는 클래스들이고, 실행 예외는 **RuntimeException을 상속**받은 클래스들이다.
- RuntimeException 역시 Exception을 상속받지만, JVM은 RuntimeException을 상속했는지 여부를 보고 실행 예외를 판단한다.

# 2. 실행 예외

- 실행 예외는 자바 컴파일러가 체크를 하지 않기 때문에 오로지 **개발자의 경험**에 의해서 예외 처리 코드를 삽입해야 한다.
- 만약 개발자가 실행 예외에 대해 예외 처리 코드를 넣지 않았을 경우, 해당 예외가 발생하면 프로그램은 곧바로 종료된다.
- 자바 프로그램에서 자주 발생되는 실행 예외이므로 언제 발생되고, 어떤 오류 메시지가 출력되는지 잘 알아둘 필요가 있다.

## NullPointerException

- 이것은 객체 참조가 없는 상태, 즉 **null 값을 갖는 참조 변수**로 객체 접근 연산자인 도트(.)를 사용했을 때 발생한다.
- 객체가 없는 상태에서 객체를 사용하려 했으니 예외가 발생하는 것이다.

```java
public class NullPointerExceptionExample {
	public static void main(String[] args) {
        String data = null;
		System.out.println(data.toString());
	}
}
```

- 프로그램에서 예외가 발생하면 예외 메시지가 Console 뷰에 출력되면서 프로그램이 종료된다.
- Console 뷰에 출력되는 내용에는 어떤 예외가 어던 소스의 몇 번째 코드에서 발생했는지에 대한 정보가 들어있다.

## ArrayIndexOutOfBoundsException

- 배열에서 **인덱스 범위를 초과**하여 사용할 경우 발생한다.

```java
public class ArrayIndexOutOfBoundsExceptionExample {
	public static void main(String[] args) {
        String data1 = args[0];
        String data2 = args[1];

		System.out.println("args[0]: " + data1);
		System.out.println("args[1]: " + data2);
	}
}
```

## NumberFormatException

- 프로그램을 개발하다 보면 문자열로 되어 있는 데이터를 숫자로 변경하는 경우가 자주 발생한다.

반환 타입|메소드명(매개 변수)|설명
:---|:---|:---
int|Integer.parseInt(String s)|주어진 문자열을 정수로 변환해서 리턴
double|Double.parseDouble(String s)|주어진 문자열을 실수로 변환해서 리턴

- 이 메소드들은 매개값인 문자열이 숫자로 변환될 수 있다면 숫자를 리턴하지만, **숫자로 변환될 수 없는 문자가 포함**되어 있다면 발생한다.

```java
public class NumberFormatExceptionExample {
	public static void main(String[] args) {
        String data1 = "100";
        String data2 = "a100";
        
        int value1 = Integer.parseInt(data1);
        int value2 = Integer.parseInt(data2);   //NumberFormatException 발생
        
        int result = value1 + value2;
		System.out.println(data1 + " + " + data2 + " = " + result);
	}
}
```

## ClassCastException

- 타입 변환(Casting)은 상위 클래스와 하위 클래스 간에 발생하고 구현 클래스와 인터페이스 간에도 발생한다.
- 이러한 관계가 아니라면 클래스는 다른 클래스로 타입 변환할 수 없다.
- **억지로 타입 변환**을 시도할 경우 발생한다.
- ClassCastException을 발생시키지 않으려면 타입 변환 전에 타입 변환이 가능한지 **instanceof 연산자로 확인**하는 것이 좋다.
- instanceof 연산의 결과가 true이면 좌항 객체를 우항 타입으로 변환이 가능하다는 뜻이다.

```java
Animal animal = new Dog();
if (animal instanceof Dog) {
	Dog dog = (Dog) animal;
} else if (animal instanceof Cat) {
	Cat cat = (Cat) animal;
}
```

# 3. 예외 처리 코드

- 프로그램에서 예외가 발생했을 경우 프로그램의 갑작스러운 종료를 막고, **정상 실행을 유지**할 수 있도록 처리하는 코드를 예외 처리 코드라고 한다.
- 예외 처리 코드는 **try-catch-finally 블록을 이용**한다.
- try-catch-finally 블록은 생성자 내부와 메소드 내부에서 작성되어 일반 예외와 실행 예외가 발생할 경우 예외 처리를 할 수 있도록 해준다.

![try-catch-finally](https://user-images.githubusercontent.com/47477359/144701268-282fcb33-9bcb-422d-88a8-41839a0ff7e4.png)

- try 블록에는 **예외 발생 가능 코드가 위치**한다.
- try 블록의 코드가 정상 실행되면 catch 블록의 코드는 실행되지 않고 finally 블록의 코드를 실행한다.
- 만약 try 블록의 코드에서 예외가 발생하면 즉시 실행을 멈추고 catch 블록으로 이동하여 **예외 처리 코드를 실행**하고, finally 블록의 코드를 실행한다.
- 예외 발생 여부와 상관없이 **항상 실행할 내용**이 있을 경우에만 finally 블록을 작성해주면 되므로, 생략 가능하다.

```java
public class TryCatchFinallyRuntimeExceptionExample {
	public static void main(String[] args) {
        String data1 = "a";
        String data2 = "b";
		
        try {
        	int value1 = Integer.parseInt(data1);
        	int value2 = Integer.parseInt(data2);
        	int result = value1 + value2;
			System.out.println(data1 + " + " + data2 + " = " + result); 
        } catch (NumberForamtException e) {
			System.out.println("숫자로 변환할 수 없습니다.");
		} finally {
			System.out.println("다시 실행하세요.");
		}
	}
}
```

# 4. 예외 종류에 따른 처리 코드

## 다중 catch

- try 블록 내부는 다양한 종류의 예외가 발생할 수 있다.
- 발생되는 예외별로 예외 처리 코드를 다르게 하려면 다중 catch 블록을 작성하면 된다.
- catch 블록의 예외 클래스 타입은 try 블록에서 발생된 예외의 종류를 말하는데, try 블록에서 해당 타입의 예외가 발생하면 catch 블록을 실행하도록 되어 있다.
- catch 블록이 여러 개라 할지라도 **단 하나의 catch 블록만 실행**된다.
- 그 이유는 try 블록에서 동시다발적으로 예외가 발생하지 않고, 하나의 예외가 발생하면 **즉시 실행을 멈추고 해당 catch 블록으로 이동**하기 떄문이다.

```java
public class CatchByExceptionKindExample {
	public static void main(String[] args) {
        try {
        	String data1 = args[0];
        	String data2 = args[1];
        	int value1 = Integer.parseInt(data1);
        	int value2 = Integer.parseInt(data2);
        	int result = value1 + value2;
			System.out.println("result: " + result);
		} catch (ArrayIndexOutOfBoundsException e) {
			System.out.println("실행 매개값의 수가 부족합니다.");
			System.out.println("[실행 방법]");
			System.out.println("java CatchByExceptionKindExample num1 num2");
		} catch (NumberFormatException e) {
			System.out.println("숫자로 변환할 수 없습니다.");
		} finally {
			System.out.println("다시 실행하세요.");
		}
	}
}
```

## catch 순서

- 다중 catch 블록을 작성할 때 주의할 점은 상위 예외 클래스가 하위 예외 클래스보다 아래쪽에 위치해야 한다.
- try 블록에서 예외가 발생했을 때, 예외를 처리해줄 catch 블록은 위에서부터 차례대로 검색된다.
- 만약 상위 예외 클래스의 catch 블록이 위에 있다면, 하위 예외 클래스의 catch 블록은 실행되지 않는다.
- 왜냐하면 하위 예외는 **상위 예외를 상속**했기 때문에 상위 예외 타입도 되기 때문이다.

```java
public class CatchOrderExample {
	public static void main(String[] args) {
        String data1 = "a";
        String data2 = "b";
		
        try {
        	int value1 = Integer.parseInt(data1);
        	int value2 = Integer.parseInt(data2);
        	int result = value1 + value2;
			System.out.println(data1 + " + " + data2 + " = " + result); 
        } catch (NumberForamtException e) {
			System.out.println("숫자로 변환할 수 없습니다.");
        } catch (Exception e) {
			System.out.println("실행에 문제가 있습니다.");
		} finally {
			System.out.println("다시 실행하세요.");
		}
	}
}
```

## 멀티 catch

- 자바 7부터 하나의 catch 블록에서 여러 개의 예외를 처리할 수 있도록 멀티 catch 기능을 추가했다.
- catch 괄호() 안에 동일하게 처리하고 싶은 예외를 |로 연결하면 된다.

```java
public class CatchOrderExample {
	public static void main(String[] args) {
        String data1 = "a";
        String data2 = "b";
		
        try {
        	int value1 = Integer.parseInt(data1);
        	int value2 = Integer.parseInt(data2);
        	int result = value1 + value2;
			System.out.println(data1 + " + " + data2 + " = " + result); 
        } catch (NumberForamtException | ArrayIndexOutOfBoundsException e) {
			System.out.println("실행 매개값의 수가 부족하거나 숫자로 변환할 수 없습니다.");
        } catch (Exception e) {
			System.out.println("실행에 문제가 있습니다.");
		} finally {
			System.out.println("다시 실행하세요.");
		}
	}
}
```

# 5. 자동 리소스 닫기

- 자바 7에서 새로 추가된 **try-with-resources**를 사용하면 예외 발생 여부와 상관없이 사용했던 리소스 객체(각종 입출력 스트림, 서버 소켓, 소켓, 각종 채널)의 **close() 메소드를 호출**해서 안전하게 리소스를 닫아준다.
- try {}에서 예외가 발생하면 우선 close()로 리소스를 닫고 catch 블록을 실행한다.
- 사용하기 위한 조건이 있는데, 리소스 객체는 **java.lang.AutoCloseable 인터페이스를 구현**하고 있어야 한다.
- AutoCloseable에는 close() 메소드가 정의되어 있는데 try-with-resources는 바로 이 close() 메소드를 자동 호출한다.

```java
public class FileInputStream implements AutoCloseable {
	private String file;
	
	public FileInputStream(String file) {
		this.file = file;
    }
    
    public void read() {
		System.out.println(file + "을 읽습니다.");
    }
    
    @Override
    public void close() throws Exception {
		System.out.println(file + "을 닫습니다.");
    }
}

public class TryWithResourcesExample {
	public static void main(String[] args) {
        try (FileInputStream fis = new FileInputStream("file.txt")) {
        	fis.read();
        	throw new Exception();
		} catch (Exception e) {
			System.out.println("예외 처리 코드가 실행되었습니다.");
		}
	}
}
```

# 6. 예외 떠넘기기

- 메소드 내부에서 예외가 발생할 수 있는 코드를 작성할 때 try-catch 블록으로 예외를 처리하는 것이 기본이지만, 경우에 따라서는 메소드를 호출한 곳으로 예외를 떠넘길 수도 있다.
- throws 키워드는 메소드 선언부 끝에 작성되어 메소드에서 처리하지 않은 **예외를 호출한 곳으로 떠넘기는 역할**을 한다.
- throws 키워드 뒤에는 떠넘길 예외 클래스를 쉼표로 구분해서 나열해주면 된다.

```java
리턴타입 메소드명(매개변수, ...) throws 예외클래스1, 예외클래스2, ... {
}
```

- throws 키워드가 붙어있는 메소드는 **반드시 try 블록 내에서 호출**되어야 한다.
- 그리고 catch 블록에서 떠넘겨 받은 예외를 처리해야 한다.

```java
public class ThrowsExample {
	public static void main(String[] args) {
        try {
        	findClass();
		} catch (ClassNotFoundException e) {
			System.out.println("클래스가 존재하지 않습니다.");
		}
	}
	
	public static void findClass() throws ClassNotFoundException {
		Class clazz = Class.forName("java.lang.String2");
    }
}
```

- main() 메소드에서도 throws 키워드를 사용해서 예외를 떠넘길 수 있는데, 결국 JVM이 최종적으로 예외 처리를 하게 된다.
- JVM은 예외의 내용을 콘솔에 출력하는 것으로 예외 처리를 한다.

```java
public static void main(String[] args) throws ClassNotFoundException {
	findClass();
}
```

- main() 메소드에서 throws Exception을 붙이는 것은 좋지 못한 예외 처리 방법이다.
- 프로그램 사용자는 프로그램이 알 수 없는 예외 내용을 출력하고 종료되는 것을 좋아하지 않는다.
- 그렇기 때문에 main()에서 try-catch 블록으로 예외를 최종 처리하는 것이 바람직하다.

# 7. 사용자 정의 예외와 예외 발생

- 잔고 부족 예외와 같이 애플리케이션 서비스와 관련된 예외를 애플리케이션 예외라고 한다.
- 애플리케이션 예외는 **개발자가 직접 정의**해서 만들어야 하므로 사용자 정의 예외라고도 한다.

## 사용자 정의 예외 클래스 선언

- 사용자 정의 예외 클래스는 컴파일러가 체크하는 일반 예외로 선언할 수도 있고, 컴파일러가 체크하지 않는 실행 예외로 선언할 수도 있다.
- 일반 예외로 선언할 경우 Exception을 상속하면 되고, 실행 예외로 선언할 경우 RuntimeException을 상속하면 된다.

```java
public class XXXException extends [ Exception | RuntimeException ] {
	public XXXException() { }
	public XXXException(String message) { super(message); }
}
```

- 사용자 정의 예외 클래스 이름은 Exception으로 끝나는 것이 좋다.
- 사용자 정의 예외 클래스도 필드, 생성자, 메소드 선언들을 포함할 수 있지만 대부분 생성자 선언만을 포함한다.
- 생성자는 두 개를 선언하는 것이 일반적인데, 하나는 매개 변수가 없는 기본 생성자이고, 다른 하나는 예외 발생 원인(예외 메시지)을 전달하기 위해 String 타입의 매개 변수를 갖는 생성자이다.
- String 타입의 매개 변수를 갖는 생성자는 상위 클래스의 생성자를 호출하여 예외 메시지를 넘겨준다.
- 예외 메시지의 용도는 catch {} 블록의 예외 처리 코드에서 이용하기 위해서이다.

## 예외 발생시키기

- 사용자 정의 예외 또는 자바 표준 예외를 코드에서 발생시키는 방법은 다음과 같다.

```java
throw new XXXException();
throw new XXXException("메시지");
```

- 예외 발생 코드를 가지고 있는 메소드는 내부에서 try-catch 블록으로 예외를 처리할 수 있지만, 대부분은 자신을 호출한곳에서 예외를 처리하도록 throws 키워드로 예외를 떠넘긴다.

```java
public class Account {
	private long balance;
	
	public Account() { }
	
	public long getBalance() {
		return balance;
    }
    
    public void deposit(int money) {
		balance += money;
    }
    
    public void withdraw(int money) throws BalanceInsufficientException {
		if (balance < money) {
			throw new BalanceInsufficientException("잔고부족: " + (money - balance) + " 모자람");
		}
		balance -= money;
    }
}
```

# 8. 예외 정보 얻기

- try 블록에서 예외가 발생하면 예외 객체는 catch 블록의 매개 변수에서 참조하게 되므로 매개 변수를 이용하면 예외 객체의 정보를 알 수 있다.
- 모든 예외 객체는 Exception 클래스를 상속하기 때문에 Exception이 가지고 있는 메소드들을 모든 예외 객체에서 호출할 수 있다.
- 그중에서도 가장 많이 사용되는 메소드는 getMessage()와 printStackTrace()이다.
- 예외를 발생시킬 때 다음과 같이 String 타입의 메시지를 갖는 생성자를 이용하였다면, 메시지는 자동적으로 예외 객체 내부에 저장된다.

```java
throw new XXXException("예외 메시지");
```

- 예외 메시지는 다음과 같이 catch 블록에서 getMessage() 메소드의 리턴값으로 얻을 수 있다.
- printStackTrace()는 메소드 이름에서도 알 수 있듯이 예외 발생 코드를 추적해서 모두 콘솔에 출력한다.
- 어떤 예외가 발생했는지 상세하게 출력해주기 때문에 프로그램을 테스트하면서 오류를 찾을 때 활용된다.

```java
public class AccountExample {
	public static void main(String[] args) {
        Account account = new Account();
        account.deposit(10000);
		System.out.println("예금액: " + account.getBalace());
        
		try {
			account.withdraw(30000);
		} catch (BalanceInsufficientException e) {
			String message = e.getMessage();
			System.out.println(message);
			System.out.println();
            e.printStackTrace();
		}
	}
}
```
